version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "books_crud"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass1"
    ports:
      - "5432:5432"